# Generated by Django 2.1 on 2018-08-27 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsbanners',
            old_name='event_name',
            new_name='title',
        ),
    ]
