# Generated by Django 2.1 on 2018-08-27 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningapp', '0002_auto_20180827_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsbanners',
            old_name='title',
            new_name='name',
        ),
    ]
